lib/AST/ASTImporter.cpp
unittests/AST/ASTImporterTest.cpp

This commit adds a visitor for AtomicType nodes in ASTNodeImporter, so
that AtomicType nodes can be imported. Also added a test for this
functionality.
This commit fixes #10.

Add support for importing Atomic nodes

---

lib/AST/ASTImporter.cpp

It is already checked after the cast.

use dyn_cast_or_null where the import can result null pointer 

---

tools/xtu-build-new/lib/memprof_analyze.py
tools/xtu-build-new/xtu-analyze.py

The current implementation is not working if valgrind is not installed even if I don't want memory profile

Only search for valgrind if it is required + pep8

---

lib/AST/ASTImporter.cpp

Couple of builtin types will no longer fail using this.

Implement TypeTraitExpr importing in ASTImporter

---

lib/StaticAnalyzer/Core/ExprEngine.cpp

Using the expansion location models the execution more precisely, the coverage reports obtained this way will be saner and easier to interpret.

Use expansion locations rather than spelling locations to have nicer coverage reports.

---

lib/AST/ASTImporter.cpp
test/ASTMerge/struct/Inputs/struct1.c
test/ASTMerge/struct/Inputs/struct2.c

In case the unnamed struct is not inside a record the analyzer will give an error about importing more then one of them since it would be checked only in line 3065 (IsStructuralMatch function call which complain parameter is true by default).

check unnamed struct equivalence if it isnt inside a record

---

tools/xtu-analysis/xtu-analyze.py
tools/xtu-analysis/xtu-build.py

Let the user set tricky threading factors. Let's stay with a simple one.

We don't want to be smarter than the user.

---

test/ASTMerge/category/test.m
test/ASTMerge/class-template-partial-spec/test.cpp
test/ASTMerge/class-template/test.cpp
test/ASTMerge/class/Inputs/class_member_order.cpp
test/ASTMerge/class/nothing.cpp
test/ASTMerge/enum/test.c
test/ASTMerge/function/test.c
test/ASTMerge/interface/test.m
test/ASTMerge/namespace/test.cpp
test/ASTMerge/property/test.m
test/ASTMerge/struct/test.c
test/ASTMerge/typedef/test.c
test/ASTMerge/var/test.c

This commit also fixes tests which were failing because we converted some errors into warnings.

 Add tests for struct field order importing. Fixes #171.

---

lib/StaticAnalyzer/Core/PathDiagnostic.cpp

We experienced a regression on the number of successes when analyzing vim. There were some crashes during emitting the reports due to sometimes we could not query the corresponding file entry for a source location. Unfortunately, it is very hard to synthesize a test case for this problem, but I tested this code on vim and it seems to solve the problem.

Fix a crash due to invalid file ids

---

include/clang/AST/ASTImporter.h
include/clang/Tooling/CrossTranslationUnit.h
lib/AST/ASTImporter.cpp
lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp
lib/Tooling/CrossTranslationUnit.cpp
test/Analysis/Inputs/externalFnMap_usr.txt
test/Analysis/Inputs/xtu-other.cpp
test/Analysis/xtu-main_usr.cpp

This way the analyzer won't inline the badly imported functions with unsupported AST nodes.

Track functions with unsupported AST nodes

---

tools/scan-build-py/libscanbuild/analyze.py
tools/scan-build-py/libscanbuild/clang.py
tools/scan-build-py/tests/unit/test_analyze.py

Now, scan-build also generates its files in platform subdirs under ctu-dir and takes care of calling clang with correct ctu-dir=path/platform-subdir  
It leaves triplet arch out from function names in maps.
It also uses now the full triplet instead of just the arch name.
(Generally follows the conventions done in codechecker now.)

Fixing scan-build triplet problem

---

include/clang/Driver/CC1Options.td
include/clang/StaticAnalyzer/Core/AnalyzerOptions.h
include/clang/Tooling/CrossTranslationUnit.h
lib/Frontend/CompilerInvocation.cpp
lib/StaticAnalyzer/Core/CallEvent.cpp
lib/Tooling/CrossTranslationUnit.cpp
test/Analysis/xtu-main_usr.cpp

During CTU, if a function definition is needed from another TU and the
pch dump is present we display the name of the source file from which
the dump is generated (.ast extension removed).
This is needed to be able to collect those TUs which are used during the
analysis; in case of a crash we can package these files into the failure
zip.

Display loaded files for ctu analysis

---

include/clang/Basic/DiagnosticASTKinds.td
lib/AST/ASTImporter.cpp

This PR gives a warning when we want to remove a `Decl` from a `DeclContext` where it is not present (in `ImportDeclContext()`). We do not try to remove the unlinked `Decl` (and fail), rather we just issue the warning and we go on. We assume the information given in the warnings will guide us towards which AST nodes are imported wrongly into a `DeclContext`. These may be independent cases.
During minilink analysis I received the following missing declarations:
```
ANALYZE (CTU loaded AST for source file): ./report_debug/ctu-dir/powerpc/ast/home/egbomrt/WORK/DebugCrashes/minilink/reports/bns__2018_01_17__11_48_26/failed/UpgradeManager.cc_eb08be5f0e35d8a98c17ce0ecb505989/sources-root/local/scratch/repos/ML66/ml66_nps/nps/bns_app_src/platform/eqm/su/src/Snmp.cc
warning: Missing Decl in …
```

Remove Decl from DeclContext only if present

---

lib/AST/ASTImporter.cpp
lib/AST/DeclBase.cpp
test/Import/template-specialization/test.cpp

Unfortunately the TypeAliasDecl fix was not proper in #255 . Fixing now.

Fix error with TypeAliasDecl import

---

include/clang/AST/DeclBase.h
lib/AST/ASTImporter.cpp
unittests/AST/ASTImporterTest.cpp

Fixes #262 
The crux of the problem was that during import we did not set up the `IdentifierNamespace` of the `Decl`s. This caused that the imported `ToFriendD` had wrong IDNS value, which in turn caused the assertion in `setObjectOfFriendDecl()`.

Fix import of FriendDecl

---

lib/AST/ASTImporter.cpp
unittests/AST/ASTImporterTest.cpp

Fix ClassTemplateSpecialization in wrong DC

---

lib/AST/ASTImporter.cpp
lib/Tooling/CrossTranslationUnit.cpp
test/Analysis/Inputs/xtu-other.c
unittests/AST/ASTImporterTest.cpp

Importing such a recursive structure is impossible without architectural changes in the importer. But this fix avoids crash and registers the problem.

ASTImport crash fix importing struct in function params

---

unittests/AST/ASTImporterTest.cpp

The new test cases which use `Fixture::getImportedDecl()` of `Fixture::getTuDecl()` may crash if we want to dump() the AST after the return of the mentioned functions. This is because `SourceManager` references to a buffer which is given during the AST creation, but that buffer is live only before returning those mentioned functions.

Fix liveness problem in ASTImporterTest

---

lib/AST/ASTImporter.cpp
unittests/AST/ASTImporterTest.cpp

The const_cast was not covered by the AST importer.
Fixes #273

Add const_cast to AST importer

---

tools/clang-func-mapping/ClangFnMapGen.cpp

The function collector shouldn't collect function names from files which
don't compile because this causes further errors in CTU analysis. Namely
the AST dump files can't be created because of the compilation error,
but the external function map file contains symbols which should be in
these. The error occurs when the AST importer tries to import these
function definitions from the non-existing AST dump file.
Fix

Don't collect functions from non-compiling files

---

lib/AST/ASTImporter.cpp
unittests/AST/ASTImporterTest.cpp
unittests/AST/CMakeLists.txt
unittests/AST/DeclMatcher.h
unittests/AST/Language.h
unittests/AST/MatchVerifier.h
unittests/AST/StructuralEquivalenceTest.cpp

* Added unit tests for structural eq, which explores a few errors. E.g. `char foo;` and `signed char foo;` should not be eq. This has to be corrected in an other PR.

Add unit tests for structural equivalence

---

lib/AST/ASTImporter.cpp
test/ASTMerge/class-template/Inputs/class-template3.cpp
test/ASTMerge/class-template/test.cpp
unittests/AST/ASTImporterTest.cpp

In some circumstances it is possible that a FunctionDecl is
imported duplicatedly during ASTNodeImporter::VisitFunctionDecl.
Checks are added to prevent overwrite of existing imported
FunctionDecl. New assertions are added to check for this
problem too. VisitStaticAssertDecl was updated with same check
because it was discovered that the problem happens here too.
This is probably a quick fix for the problem (does not solve the root cause).

ASTImporter fix for recursive import of function

---

lib/StaticAnalyzer/Checkers/CStringChecker.cpp

in CStringChecker.cpp:
If the CStringOutOfBounds check is disabled do not perform the check in `CheckLocation` (and do not use the in this case empty string).

fix for assertion getCheckName '!CheckName.empty()'

---

lib/StaticAnalyzer/Checkers/CStringChecker.cpp

Reverts Ericsson/clang#302
Solution at  https://reviews.llvm.org/rC323052 will be used instead.

Revert "fix for assertion getCheckName '!CheckName.empty()'"

---

lib/AST/ASTImporter.cpp
unittests/AST/ASTImporterTest.cpp
unittests/AST/DeclMatcher.h

PrevDecl was not set for ClassTemplateSpecializationDecl. This would mess up the canonical decl for the imported declaration and mislead the structural equivalence checker code.
Moreover, we need to set the PrevDecl of a CXXRecordDecl in the Create static method, not afterwards. This ensures that the TypeForDecl field is initialized correctly and we do not create a new type each time we import a declaration for an already existing one.

Fix more bogus ODR warning errors.

---

lib/AST/ASTImporter.cpp
unittests/AST/ASTImporterTest.cpp

This patch fixes lots of ODR violation warnings that complain about incompatible types while analyzing xerces. Unfortunately, I could not synthesize a minimal example to reproduce the error, this is the reason for the lack of tests.

Fix warnings some ODR warnings in analyzing xerces.

---

lib/AST/ASTImporter.cpp
unittests/AST/ASTImporterTest.cpp

Fix for assertion
"Try to import an already imported Decl"
that occurs through calling
ASTNodeImporter::VisitClassTemplateDecl.
Fix for #312 .

ASTImporter::Imported - VisitClassTemplateDecl assertion fix

---

lib/AST/ASTImporter.cpp
unittests/AST/ASTImporterTest.cpp

Temporarily disable the fix of importing the prototype of recursive functions #313 . This fix causes serious degradation in Xerces. We go on now with possible multiple definitions (violating ODR) until we came up with the proper long term solution. That solution will probably solve #327 and #282 as well.

Revert to not support proto of recursive function

---

include/clang/AST/ASTImporter.h
lib/AST/ASTImporter.cpp
test/ASTMerge/class/test.cpp
unittests/AST/ASTImporterTest.cpp

With this PR when any Decl of a redeclaration chain is imported then we bring in the whole declaration chain.
The chain is imported as it is in the "from" tu, the order of the redeclarations are kept.
I also changed the lookup logic in order to find friends, but first making them visible in their declaration context.
We may have long redeclaration chains if all TU contains the same prototype, therefore I made some measurements on Xerces to see the scale of degradation.
Also, as further work we could squash redundant prototypes, but first let's see if functionality is working properly; then should we optimize.
Regression results on Xerces:
Baseline (*) with all asserts:
- successfully analyzed: 15
- "try to import already imported" assert: 291
- "should have body" assert: 42
Baseline (*) …

Import the whole FunctionDecl chain

---

lib/AST/ASTImporter.cpp

Fixes #338 
This reduces "try to import already imported decl" assert to `0` on Xerces. (On the baseline we had `6` of these).
Unfortunately, I could not synthesize any unit test for this.

Fix redundant import of VarDecl

---

lib/CrossTU/CrossTranslationUnit.cpp

We need to drop the ".ast" extension in order to pass CTU failure tests in CodeChecker.

Drop .ast extension

---

lib/AST/ASTImporter.cpp
unittests/AST/ASTImporterTest.cpp

There is an import path, where the templated `RecordDecl` of a `ClassTemplateDecl` with a definition gets imported before the `ClassTemplateDecl` itself.
In this case, lookup may find a forward declaration for the very same `ClassTemplateDecl`.
However, `IsStructuralMatch` falsely reports structurally equivalence in between the forward decl and the definition. This is because `IsStructuralMatch` does not check member functions, only data members! 
By having this false structural match the assert fires on the `MapImport` of the templated decl because we want to assign a forward decl to the definition which we had already imported.
Either we change `IsStructuralMatch` or we add an extra check for this case.
I chose the latter, because changing `IsStructuralMatch` would have much broader …

Fix already imported assert in class templates

---

include/clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h
lib/StaticAnalyzer/Core/BugReporter.cpp
lib/StaticAnalyzer/Core/BugReporterVisitors.cpp

This visitor was missing from `ctu-clang6` branch, but it was the part of `ctu-clang5`

Adding SpecialReturnValueBRVisitor

---

lib/AST/ASTImporter.cpp
lib/AST/DeclBase.cpp
test/Import/template-specialization/Inputs/T.cpp
test/Import/template-specialization/test.cpp
unittests/AST/ASTImporterTest.cpp

In case of function template specializations, their `DeclContext` was not set up correctly.
Also, the redecl chain was not set up. This caused an error since #329 where we just simply removed the related tests. For upstreaming any redecl chain related change, we had to re enable those tests and implement the redecl chain for specializations too.

Import redecl chain of function template specializations
