tools/xtu-build-new/xtu-analyze.py
Add check for both clang, and analyze-cc executables. Behaviour: if a path is specified via arguments, and no executable is found on that path, an error is shown (no other searches are performed, since if the specified path is not correct we should not search the environment). If no arguments are specified for that executable, the PATH environment is searched.
=> Add executable path checking

tools/xtu-build-new/xtu-analyze.py
Show progress by printing files being added to the work queue.
=> Add status report to show files being analyzed

test/Analysis/Inputs/externalFnMap.txt, test/Analysis/Inputs/xtu-chain.cpp, test/Analysis/Inputs/xtu-other.cpp, test/Analysis/xtu-main.cpp
Basic stuff for issue: https://github.com/dkrupp/clang/issues/32
=> add test cases xtu-import

lib/AST/ASTImporter.cpp, test/Analysis/Inputs/externalFnMap2.txt, test/Analysis/Inputs/xtu-other.c, test/Analysis/xtu-main.c
=> A fix to importing structs.

tools/xtu-build-new/xtu-analyze.py, utils/analyzer/MergeCoverage.py
Possibility to diff the coverage of two analysis runs.
=> Diff coverage

tools/xtu-build-new/lib/memprof_analyze.py, tools/xtu-build-new/xtu-analyze.py
previous pull request was deleted and this was created instead.
All comments addressed and the helper script rewritten to python.
=> valgrind memory profiling feature added

lib/AST/ASTImporter.cpp, test/ASTMerge/struct/Inputs/struct1.c, test/ASTMerge/struct/Inputs/struct2.c, test/ASTMerge/struct/test.c, test/Analysis/Inputs/externalFnMap2.txt, test/Analysis/Inputs/xtu-other.c, test/Analysis/xtu-main.c
incompatible types problem fixes
=> Astimporter improvements

tools/ctu-analysis/ctu-build.py
Solves https://github.com/Ericsson/clang/issues/123
=> Deduplicate mangled names

lib/AST/ASTContext.cpp, tools/ctu-analysis/ctu-analyze.py, tools/ctu-analysis/ctu-build.py, tools/ctu-analysis/tests/caller.c, tools/ctu-analysis/tests/lib 2.c, tools/ctu-analysis/tests/lib.c, tools/ctu-analysis/tests/lib.h, tools/ctu-analysis/tests/lib2.h, tools/ctu-analysis/tests/test1.sh, tools/ctu-analysis/tests/test2.sh, tools/ctu-analysis/tests/test3.sh
=> Spaces in source files were not handled properly. Now this is fixed.

lib/AST/ASTImporter.cpp, unittests/AST/ASTImporterTest.cpp
Implementation and test cases added.
=> support DependentScopeDeclRefExpr and DependentNameType. Fixes #137 #138

lib/AST/ASTImporter.cpp, unittests/AST/ASTImporterTest.cpp
This also went into https://reviews.llvm.org/D39247 so it has its place here as well.
=> ASTImporter TypeAliasTemplate unit tests

lib/AST/ASTImporter.cpp, lib/AST/ASTStructuralEquivalence.cpp, unittests/AST/ASTImporterTest.cpp
Fixing importing template functions and methods problems. Fixes #176 .
=> Template function import fixes

lib/AST/ASTImporter.cpp, unittests/AST/ASTImporterTest.cpp
=> Get the almost upstream version of importing TypeTraitExpr.

tools/scan-build-py/libscanbuild/analyze.py, tools/scan-build-py/libscanbuild/arguments.py, tools/scan-build-py/libscanbuild/clang.py, tools/scan-build-py/libscanbuild/report.py, tools/scan-build-py/tests/unit/test_clang.py
All problems have been addressed. It also passes the current nosetests in the repo + did some manual testing. @Xazax-hun after you updating the patch, can I still set the Done flags in the comments or only you can do it in the same round?
=> Modifications for the review of George Karpenkov

lib/AST/DeclBase.cpp, unittests/AST/ASTImporterTest.cpp
=> Do not try to remove invisible Decls from DeclContext

tools/scan-build-py/libscanbuild/analyze.py, tools/scan-build-py/libscanbuild/arguments.py
Some more fixes from reviews on phabricator.
=> Nicer serialization back from JSON

lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp
=> Remove Linux dependency and unused function

lib/AST/ASTImporter.cpp, unittests/AST/ASTImporterTest.cpp
=> Import size of pack expressions

lib/AST/ASTImporter.cpp, unittests/AST/ASTImporterTest.cpp
=> Support importing DependentTemplateSpecializationType AST Node

include/clang/Basic/DiagnosticFrontendKinds.td, lib/Tooling/CrossTranslationUnit.cpp, test/Analysis/xtu-different-triples.c
=> Add check for incompatible lang opts

lib/AST/ASTImporter.cpp, unittests/AST/ASTImporterTest.cpp
=>  Supporting CXXOperatorCallExpr import in ASTImporter

lib/Tooling/CrossTranslationUnit.cpp
=> Strip file ending only when reading from pch

lib/AST/ASTImporter.cpp, unittests/AST/ASTImporterTest.cpp
=> Fix import CXXTemporaryObjectExpr.

lib/AST/ASTImporter.cpp, unittests/AST/ASTImporterTest.cpp
Bring in important changes from master.
=> Llvm master rebase

lib/AST/ASTImporter.cpp, test/ASTMerge/class-template/test.cpp, unittests/AST/ASTImporterTest.cpp
=> Fix missing implict CXXRecordDecl

lib/AST/ASTImporter.cpp, unittests/AST/ASTImporterTest.cpp
=> Fix missing implicit CXXRecordDecl in ClassTemplateSpecializationDecl

unittests/AST/StructuralEquivalenceTest.cpp
@martong You like these, aren't you? :)
=> Build fix for StructuralEquivalenceTest

unittests/AST/ASTImporterTest.cpp
We do import function prototypes in an incorrect way. For some reason we just import the definition. In case of a recursive function after the import we end up having two definition nodes which are structurally equivalent. This violates ODR and can cause assertions and fatal errors in any code which works on the AST.
```
[ RUN      ] Fixture.DISABLED_ImportPrototypeOfFunction
../../git/llvm/tools/clang/unittests/AST/ASTImporterTest.cpp:1337: Failure
Value of: ToPrototypeFD != ToDefinitionFD
Actual: false
Expected: true
../../git/llvm/tools/clang/unittests/AST/ASTImporterTest.cpp:1338: Failure
Value of: ToPrototypeFD->doesThisDeclarationHaveABody()
Actual: true
Expected: false
../../git/llvm/tools/clang/unittests/AST/ASTImporterTest.cpp:1340: Failure
Value of: …
```
=> Add unit tests for importing prototype properly

lib/AST/ASTImporter.cpp, unittests/AST/ASTImporterTest.cpp
=> Fix import of recursive function prototype

tools/scan-build-py/libscanbuild/analyze.py
This option was added to the Static Analyzer in 3558c29dffdbd1eabf0cb17d9b4e532c625e5595 , however, the running script was not updated.
=> Adding enable naive CTU analyzer option to analyze-build.

unittests/AST/ASTImporterTest.cpp
- Fixes #308
- Makes it possible to write unit tests where we import from two different source files with different file names. Previously all file names were "input.cc".
=> Fix unit test SourceLoc errors

lib/AST/ASTImporter.cpp, unittests/AST/ASTImporterTest.cpp, unittests/AST/DeclMatcher.h
This is the second attempt to fix #282
=> Fix recursive function with prototype

lib/AST/ASTImporter.cpp, unittests/AST/ASTImporterTest.cpp
I compared the upstream version of the ASTImporter to our version and eliminated some differences. This should bring us closer to upstream. It might fix some bugs, there are some code style improvements and also it will make it easier to port our changes to clang 6 in the future.
It also uncovered some differences that might need some investigation. Also, some tests were missing.
=> Move closer to upstream codebase.

include/clang/AST/ASTImporter.h, lib/AST/ASTImporter.cpp, test/Analysis/Inputs/externalFnMap_usr.txt, test/Analysis/Inputs/xtu-other.cpp, test/Analysis/xtu-main_usr.cpp
=> Fix for importing typedefs of anonymous structures

lib/AST/ASTImporter.cpp, unittests/AST/ASTImporterTest.cpp
=> Fix redundant import of UsingShadowDecl

lib/CrossTU/CrossTranslationUnit.cpp, lib/StaticAnalyzer/Core/CallEvent.cpp
See previous PR for info: https://github.com/Ericsson/clang/pull/350
=> Avoid segfault in assert on valid FD missing case - 2nd attempt

lib/AST/ASTImporter.cpp, test/ASTMerge/injected-class-name-decl-1/Inputs/inject1.cpp, test/ASTMerge/injected-class-name-decl-1/test.cpp
=> ASTImporter InjectedClassNameType related fixes

unittests/AST/ASTImporterTest.cpp
Porting back from open source, https://reviews.llvm.org/D43967
=> Port back test imporvements

include/clang/CrossTU/CrossTranslationUnit.h, lib/CrossTU/CrossTranslationUnit.cpp
=> Fix display ctu progress
